### ISSUE TITLE
Generating object class list in classes.txt with randomized order

### ISSUE THREAD

**Issue by shure-dev** [deepinvalue/video_annotations_to_yolo#1]
Hi, thanks for your amazing work, this repo is very helpful to me

I noticed that every time I try to run your code with the same data, the code generates an object class list in classes.txt with randomized order.

If you could fix this, that would be very helpful!

**Comment by deepinvalue** [comment]
Hey @shure-dev,

Apologies for the delay, and thanks for bringing this to my attention. The reported issue is addressed now, and the labels in `classes.txt` are now generated with a consistent order.

Cheers.

**Comment by shure-dev** [comment]
@deepinvalue 
I truly appreciate your efforts, thank you
